language: objective-c

before_install:
  - brew update
  - brew install python
  - brew install python3
  - brew install valgrind
  - git submodule update --init --recursive
  - make test
  - pip install coverage coveralls
  - python setup.py install

script:
  - DYLD_LIBRARY_PATH=libtap ./test
  - python tests/test.py
  
after_success:
  - coveralls --exclude usr --exclude tests/test.cpp  --exclude cxx/main.cpp --exclude cxx/ReedSolomon.hpp --exclude data --exclude libtap --gcov-options '\-lp'
  - make clean
  - make 
  - time ./reedSolomon e data/rand32m.dat
  - ./reedSolomon m
  - time ./reedSolomon d data/rand32m.dat
  - DYLD_LIBRARY_PATH=libtap G_SLICE=always-malloc G_DEBUG=gc-friendly  valgrind -v --tool=memcheck --leak-check=full --show-reachable=yes --log-file=a.log --num-callers=40 ./reedSolomon e data/rand32m.dat
  - cat a.log
  - ./reedSolomon m
  - DYLD_LIBRARY_PATH=libtap G_SLICE=always-malloc G_DEBUG=gc-friendly  valgrind -v --tool=memcheck --leak-check=full --show-reachable=yes --log-file=a.log --num-callers=40 ./reedSolomon d data/rand32m.dat
  - cat a.log
