language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'

before_install:
  - git submodule update --init --recursive
  - make test
  - make python
  - sudo pip install cpp-coveralls
  - sudo apt-get -qq update
  - sudo apt-get install valgrind
  
script:
  - LD_LIBRARY_PATH=libtap ./test
  - PYTHONPATH=. python tests/test.py
  
after_success:
  - coveralls --exclude usr --exclude tests/test.cpp  --exclude cxx/main.cpp --exclude cxx/ReedSolomon.h --exclude data --exclude libtap --gcov-options '\-lp'
  - make clean
  - make 
  - time ./reedSolomon e data/rand32m.dat
  - ./reedSolomon m
  - time ./reedSolomon d data/rand32m.dat
  - LD_LIBRARY_PATH=libtap G_SLICE=always-malloc G_DEBUG=gc-friendly  valgrind -v --tool=memcheck --leak-check=full --show-reachable=yes --log-file=a.log --num-callers=40 ./reedSolomon e data/rand32m.dat
  - cat a.log
  - ./reedSolomon m
  - LD_LIBRARY_PATH=libtap G_SLICE=always-malloc G_DEBUG=gc-friendly  valgrind -v --tool=memcheck --leak-check=full --show-reachable=yes --log-file=a.log --num-callers=40 ./reedSolomon d data/rand32m.dat
  - cat a.log
